apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-ms-user
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-user
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70