apiVersion: v1
kind: Secret
metadata:
  name: secrets-ms-auth
type: Opaque
stringData:
  ConnectionStrings__MongoDbConnection: "mongodb+srv://fiapuser:galho123@cluster0.rudlego.mongodb.net/?appName=Cluster0"
  Jwt__SigningKey: "sAnWYnoH6TQp5lYzekQPfW2dNCZQvTQDdQMciYxz63zmu7KTjl/TTIRaIreQA/MoxEDyNPXowBY3MOmiegi07Q=="
  NEW_RELIC_LICENSE_KEY: "b84b3154946deb5277c2eb2c55a5056fFFFFNRAL"